from enum import Enum


class CountryCode(Enum):
    """An enumeration representing different categories.

    :cvar AF: "af"
    :vartype AF: str
    :cvar AL: "al"
    :vartype AL: str
    :cvar DZ: "dz"
    :vartype DZ: str
    :cvar AS: "as"
    :vartype AS: str
    :cvar AD: "ad"
    :vartype AD: str
    :cvar AO: "ao"
    :vartype AO: str
    :cvar AI: "ai"
    :vartype AI: str
    :cvar AQ: "aq"
    :vartype AQ: str
    :cvar AG: "ag"
    :vartype AG: str
    :cvar AR: "ar"
    :vartype AR: str
    :cvar AM: "am"
    :vartype AM: str
    :cvar AW: "aw"
    :vartype AW: str
    :cvar AU: "au"
    :vartype AU: str
    :cvar AT: "at"
    :vartype AT: str
    :cvar AZ: "az"
    :vartype AZ: str
    :cvar BS: "bs"
    :vartype BS: str
    :cvar BH: "bh"
    :vartype BH: str
    :cvar BD: "bd"
    :vartype BD: str
    :cvar BB: "bb"
    :vartype BB: str
    :cvar BY: "by"
    :vartype BY: str
    :cvar BE: "be"
    :vartype BE: str
    :cvar BZ: "bz"
    :vartype BZ: str
    :cvar BJ: "bj"
    :vartype BJ: str
    :cvar BM: "bm"
    :vartype BM: str
    :cvar BT: "bt"
    :vartype BT: str
    :cvar BO: "bo"
    :vartype BO: str
    :cvar BQ: "bq"
    :vartype BQ: str
    :cvar BA: "ba"
    :vartype BA: str
    :cvar BW: "bw"
    :vartype BW: str
    :cvar BV: "bv"
    :vartype BV: str
    :cvar BR: "br"
    :vartype BR: str
    :cvar IO: "io"
    :vartype IO: str
    :cvar BN: "bn"
    :vartype BN: str
    :cvar BG: "bg"
    :vartype BG: str
    :cvar BF: "bf"
    :vartype BF: str
    :cvar BI: "bi"
    :vartype BI: str
    :cvar CV: "cv"
    :vartype CV: str
    :cvar KH: "kh"
    :vartype KH: str
    :cvar CM: "cm"
    :vartype CM: str
    :cvar CA: "ca"
    :vartype CA: str
    :cvar KY: "ky"
    :vartype KY: str
    :cvar CF: "cf"
    :vartype CF: str
    :cvar TD: "td"
    :vartype TD: str
    :cvar CL: "cl"
    :vartype CL: str
    :cvar CN: "cn"
    :vartype CN: str
    :cvar CX: "cx"
    :vartype CX: str
    :cvar CC: "cc"
    :vartype CC: str
    :cvar CO: "co"
    :vartype CO: str
    :cvar KM: "km"
    :vartype KM: str
    :cvar CD: "cd"
    :vartype CD: str
    :cvar CG: "cg"
    :vartype CG: str
    :cvar CK: "ck"
    :vartype CK: str
    :cvar CR: "cr"
    :vartype CR: str
    :cvar HR: "hr"
    :vartype HR: str
    :cvar CU: "cu"
    :vartype CU: str
    :cvar CW: "cw"
    :vartype CW: str
    :cvar CY: "cy"
    :vartype CY: str
    :cvar CZ: "cz"
    :vartype CZ: str
    :cvar CI: "ci"
    :vartype CI: str
    :cvar DK: "dk"
    :vartype DK: str
    :cvar DJ: "dj"
    :vartype DJ: str
    :cvar DM: "dm"
    :vartype DM: str
    :cvar DO: "do"
    :vartype DO: str
    :cvar EC: "ec"
    :vartype EC: str
    :cvar EG: "eg"
    :vartype EG: str
    :cvar SV: "sv"
    :vartype SV: str
    :cvar GQ: "gq"
    :vartype GQ: str
    :cvar ER: "er"
    :vartype ER: str
    :cvar EE: "ee"
    :vartype EE: str
    :cvar SZ: "sz"
    :vartype SZ: str
    :cvar ET: "et"
    :vartype ET: str
    :cvar FK: "fk"
    :vartype FK: str
    :cvar FO: "fo"
    :vartype FO: str
    :cvar FJ: "fj"
    :vartype FJ: str
    :cvar FI: "fi"
    :vartype FI: str
    :cvar FR: "fr"
    :vartype FR: str
    :cvar GF: "gf"
    :vartype GF: str
    :cvar PF: "pf"
    :vartype PF: str
    :cvar TF: "tf"
    :vartype TF: str
    :cvar GA: "ga"
    :vartype GA: str
    :cvar GM: "gm"
    :vartype GM: str
    :cvar GE: "ge"
    :vartype GE: str
    :cvar DE: "de"
    :vartype DE: str
    :cvar GH: "gh"
    :vartype GH: str
    :cvar GI: "gi"
    :vartype GI: str
    :cvar GR: "gr"
    :vartype GR: str
    :cvar GL: "gl"
    :vartype GL: str
    :cvar GD: "gd"
    :vartype GD: str
    :cvar GP: "gp"
    :vartype GP: str
    :cvar GU: "gu"
    :vartype GU: str
    :cvar GT: "gt"
    :vartype GT: str
    :cvar GG: "gg"
    :vartype GG: str
    :cvar GN: "gn"
    :vartype GN: str
    :cvar GW: "gw"
    :vartype GW: str
    :cvar GY: "gy"
    :vartype GY: str
    :cvar HT: "ht"
    :vartype HT: str
    :cvar HM: "hm"
    :vartype HM: str
    :cvar VA: "va"
    :vartype VA: str
    :cvar HN: "hn"
    :vartype HN: str
    :cvar HK: "hk"
    :vartype HK: str
    :cvar HU: "hu"
    :vartype HU: str
    :cvar IS: "is"
    :vartype IS: str
    :cvar IN: "in"
    :vartype IN: str
    :cvar ID: "id"
    :vartype ID: str
    :cvar IR: "ir"
    :vartype IR: str
    :cvar IQ: "iq"
    :vartype IQ: str
    :cvar IE: "ie"
    :vartype IE: str
    :cvar IM: "im"
    :vartype IM: str
    :cvar IL: "il"
    :vartype IL: str
    :cvar IT: "it"
    :vartype IT: str
    :cvar JM: "jm"
    :vartype JM: str
    :cvar JP: "jp"
    :vartype JP: str
    :cvar JE: "je"
    :vartype JE: str
    :cvar JO: "jo"
    :vartype JO: str
    :cvar KZ: "kz"
    :vartype KZ: str
    :cvar KE: "ke"
    :vartype KE: str
    :cvar KI: "ki"
    :vartype KI: str
    :cvar KP: "kp"
    :vartype KP: str
    :cvar KR: "kr"
    :vartype KR: str
    :cvar KW: "kw"
    :vartype KW: str
    :cvar KG: "kg"
    :vartype KG: str
    :cvar LA: "la"
    :vartype LA: str
    :cvar LV: "lv"
    :vartype LV: str
    :cvar LB: "lb"
    :vartype LB: str
    :cvar LS: "ls"
    :vartype LS: str
    :cvar LR: "lr"
    :vartype LR: str
    :cvar LY: "ly"
    :vartype LY: str
    :cvar LI: "li"
    :vartype LI: str
    :cvar LT: "lt"
    :vartype LT: str
    :cvar LU: "lu"
    :vartype LU: str
    :cvar MO: "mo"
    :vartype MO: str
    :cvar MG: "mg"
    :vartype MG: str
    :cvar MW: "mw"
    :vartype MW: str
    :cvar MY: "my"
    :vartype MY: str
    :cvar MV: "mv"
    :vartype MV: str
    :cvar ML: "ml"
    :vartype ML: str
    :cvar MT: "mt"
    :vartype MT: str
    :cvar MH: "mh"
    :vartype MH: str
    :cvar MQ: "mq"
    :vartype MQ: str
    :cvar MR: "mr"
    :vartype MR: str
    :cvar MU: "mu"
    :vartype MU: str
    :cvar YT: "yt"
    :vartype YT: str
    :cvar MX: "mx"
    :vartype MX: str
    :cvar FM: "fm"
    :vartype FM: str
    :cvar MD: "md"
    :vartype MD: str
    :cvar MC: "mc"
    :vartype MC: str
    :cvar MN: "mn"
    :vartype MN: str
    :cvar ME: "me"
    :vartype ME: str
    :cvar MS: "ms"
    :vartype MS: str
    :cvar MA: "ma"
    :vartype MA: str
    :cvar MZ: "mz"
    :vartype MZ: str
    :cvar MM: "mm"
    :vartype MM: str
    :cvar NA: "na"
    :vartype NA: str
    :cvar NR: "nr"
    :vartype NR: str
    :cvar NP: "np"
    :vartype NP: str
    :cvar NL: "nl"
    :vartype NL: str
    :cvar NC: "nc"
    :vartype NC: str
    :cvar NZ: "nz"
    :vartype NZ: str
    :cvar NI: "ni"
    :vartype NI: str
    :cvar NE: "ne"
    :vartype NE: str
    :cvar NG: "ng"
    :vartype NG: str
    :cvar NU: "nu"
    :vartype NU: str
    :cvar NF: "nf"
    :vartype NF: str
    :cvar MP: "mp"
    :vartype MP: str
    :cvar NO: "no"
    :vartype NO: str
    :cvar OM: "om"
    :vartype OM: str
    :cvar PK: "pk"
    :vartype PK: str
    :cvar PW: "pw"
    :vartype PW: str
    :cvar PS: "ps"
    :vartype PS: str
    :cvar PA: "pa"
    :vartype PA: str
    :cvar PG: "pg"
    :vartype PG: str
    :cvar PY: "py"
    :vartype PY: str
    :cvar PE: "pe"
    :vartype PE: str
    :cvar PH: "ph"
    :vartype PH: str
    :cvar PN: "pn"
    :vartype PN: str
    :cvar PL: "pl"
    :vartype PL: str
    :cvar PT: "pt"
    :vartype PT: str
    :cvar PR: "pr"
    :vartype PR: str
    :cvar QA: "qa"
    :vartype QA: str
    :cvar MK: "mk"
    :vartype MK: str
    :cvar RO: "ro"
    :vartype RO: str
    :cvar RU: "ru"
    :vartype RU: str
    :cvar RW: "rw"
    :vartype RW: str
    :cvar RE: "re"
    :vartype RE: str
    :cvar BL: "bl"
    :vartype BL: str
    :cvar SH: "sh"
    :vartype SH: str
    :cvar KN: "kn"
    :vartype KN: str
    :cvar LC: "lc"
    :vartype LC: str
    :cvar MF: "mf"
    :vartype MF: str
    :cvar PM: "pm"
    :vartype PM: str
    :cvar VC: "vc"
    :vartype VC: str
    :cvar WS: "ws"
    :vartype WS: str
    :cvar SM: "sm"
    :vartype SM: str
    :cvar ST: "st"
    :vartype ST: str
    :cvar SA: "sa"
    :vartype SA: str
    :cvar SN: "sn"
    :vartype SN: str
    :cvar RS: "rs"
    :vartype RS: str
    :cvar SC: "sc"
    :vartype SC: str
    :cvar SL: "sl"
    :vartype SL: str
    :cvar SG: "sg"
    :vartype SG: str
    :cvar SX: "sx"
    :vartype SX: str
    :cvar SK: "sk"
    :vartype SK: str
    :cvar SI: "si"
    :vartype SI: str
    :cvar SB: "sb"
    :vartype SB: str
    :cvar SO: "so"
    :vartype SO: str
    :cvar ZA: "za"
    :vartype ZA: str
    :cvar GS: "gs"
    :vartype GS: str
    :cvar SS: "ss"
    :vartype SS: str
    :cvar ES: "es"
    :vartype ES: str
    :cvar LK: "lk"
    :vartype LK: str
    :cvar SD: "sd"
    :vartype SD: str
    :cvar SR: "sr"
    :vartype SR: str
    :cvar SJ: "sj"
    :vartype SJ: str
    :cvar SE: "se"
    :vartype SE: str
    :cvar CH: "ch"
    :vartype CH: str
    :cvar SY: "sy"
    :vartype SY: str
    :cvar TW: "tw"
    :vartype TW: str
    :cvar TJ: "tj"
    :vartype TJ: str
    :cvar TZ: "tz"
    :vartype TZ: str
    :cvar TH: "th"
    :vartype TH: str
    :cvar TL: "tl"
    :vartype TL: str
    :cvar TG: "tg"
    :vartype TG: str
    :cvar TK: "tk"
    :vartype TK: str
    :cvar TO: "to"
    :vartype TO: str
    :cvar TT: "tt"
    :vartype TT: str
    :cvar TN: "tn"
    :vartype TN: str
    :cvar TR: "tr"
    :vartype TR: str
    :cvar TM: "tm"
    :vartype TM: str
    :cvar TC: "tc"
    :vartype TC: str
    :cvar TV: "tv"
    :vartype TV: str
    :cvar UG: "ug"
    :vartype UG: str
    :cvar UA: "ua"
    :vartype UA: str
    :cvar AE: "ae"
    :vartype AE: str
    :cvar GB: "gb"
    :vartype GB: str
    :cvar UM: "um"
    :vartype UM: str
    :cvar US: "us"
    :vartype US: str
    :cvar UY: "uy"
    :vartype UY: str
    :cvar UZ: "uz"
    :vartype UZ: str
    :cvar VU: "vu"
    :vartype VU: str
    :cvar VE: "ve"
    :vartype VE: str
    :cvar VN: "vn"
    :vartype VN: str
    :cvar VG: "vg"
    :vartype VG: str
    :cvar VI: "vi"
    :vartype VI: str
    :cvar WF: "wf"
    :vartype WF: str
    :cvar EH: "eh"
    :vartype EH: str
    :cvar YE: "ye"
    :vartype YE: str
    :cvar ZM: "zm"
    :vartype ZM: str
    :cvar ZW: "zw"
    :vartype ZW: str
    :cvar AX: "ax"
    :vartype AX: str
    """

    AF = "af"
    AL = "al"
    DZ = "dz"
    AS = "as"
    AD = "ad"
    AO = "ao"
    AI = "ai"
    AQ = "aq"
    AG = "ag"
    AR = "ar"
    AM = "am"
    AW = "aw"
    AU = "au"
    AT = "at"
    AZ = "az"
    BS = "bs"
    BH = "bh"
    BD = "bd"
    BB = "bb"
    BY = "by"
    BE = "be"
    BZ = "bz"
    BJ = "bj"
    BM = "bm"
    BT = "bt"
    BO = "bo"
    BQ = "bq"
    BA = "ba"
    BW = "bw"
    BV = "bv"
    BR = "br"
    IO = "io"
    BN = "bn"
    BG = "bg"
    BF = "bf"
    BI = "bi"
    CV = "cv"
    KH = "kh"
    CM = "cm"
    CA = "ca"
    KY = "ky"
    CF = "cf"
    TD = "td"
    CL = "cl"
    CN = "cn"
    CX = "cx"
    CC = "cc"
    CO = "co"
    KM = "km"
    CD = "cd"
    CG = "cg"
    CK = "ck"
    CR = "cr"
    HR = "hr"
    CU = "cu"
    CW = "cw"
    CY = "cy"
    CZ = "cz"
    CI = "ci"
    DK = "dk"
    DJ = "dj"
    DM = "dm"
    DO = "do"
    EC = "ec"
    EG = "eg"
    SV = "sv"
    GQ = "gq"
    ER = "er"
    EE = "ee"
    SZ = "sz"
    ET = "et"
    FK = "fk"
    FO = "fo"
    FJ = "fj"
    FI = "fi"
    FR = "fr"
    GF = "gf"
    PF = "pf"
    TF = "tf"
    GA = "ga"
    GM = "gm"
    GE = "ge"
    DE = "de"
    GH = "gh"
    GI = "gi"
    GR = "gr"
    GL = "gl"
    GD = "gd"
    GP = "gp"
    GU = "gu"
    GT = "gt"
    GG = "gg"
    GN = "gn"
    GW = "gw"
    GY = "gy"
    HT = "ht"
    HM = "hm"
    VA = "va"
    HN = "hn"
    HK = "hk"
    HU = "hu"
    IS = "is"
    IN = "in"
    ID = "id"
    IR = "ir"
    IQ = "iq"
    IE = "ie"
    IM = "im"
    IL = "il"
    IT = "it"
    JM = "jm"
    JP = "jp"
    JE = "je"
    JO = "jo"
    KZ = "kz"
    KE = "ke"
    KI = "ki"
    KP = "kp"
    KR = "kr"
    KW = "kw"
    KG = "kg"
    LA = "la"
    LV = "lv"
    LB = "lb"
    LS = "ls"
    LR = "lr"
    LY = "ly"
    LI = "li"
    LT = "lt"
    LU = "lu"
    MO = "mo"
    MG = "mg"
    MW = "mw"
    MY = "my"
    MV = "mv"
    ML = "ml"
    MT = "mt"
    MH = "mh"
    MQ = "mq"
    MR = "mr"
    MU = "mu"
    YT = "yt"
    MX = "mx"
    FM = "fm"
    MD = "md"
    MC = "mc"
    MN = "mn"
    ME = "me"
    MS = "ms"
    MA = "ma"
    MZ = "mz"
    MM = "mm"
    NA = "na"
    NR = "nr"
    NP = "np"
    NL = "nl"
    NC = "nc"
    NZ = "nz"
    NI = "ni"
    NE = "ne"
    NG = "ng"
    NU = "nu"
    NF = "nf"
    MP = "mp"
    NO = "no"
    OM = "om"
    PK = "pk"
    PW = "pw"
    PS = "ps"
    PA = "pa"
    PG = "pg"
    PY = "py"
    PE = "pe"
    PH = "ph"
    PN = "pn"
    PL = "pl"
    PT = "pt"
    PR = "pr"
    QA = "qa"
    MK = "mk"
    RO = "ro"
    RU = "ru"
    RW = "rw"
    RE = "re"
    BL = "bl"
    SH = "sh"
    KN = "kn"
    LC = "lc"
    MF = "mf"
    PM = "pm"
    VC = "vc"
    WS = "ws"
    SM = "sm"
    ST = "st"
    SA = "sa"
    SN = "sn"
    RS = "rs"
    SC = "sc"
    SL = "sl"
    SG = "sg"
    SX = "sx"
    SK = "sk"
    SI = "si"
    SB = "sb"
    SO = "so"
    ZA = "za"
    GS = "gs"
    SS = "ss"
    ES = "es"
    LK = "lk"
    SD = "sd"
    SR = "sr"
    SJ = "sj"
    SE = "se"
    CH = "ch"
    SY = "sy"
    TW = "tw"
    TJ = "tj"
    TZ = "tz"
    TH = "th"
    TL = "tl"
    TG = "tg"
    TK = "tk"
    TO = "to"
    TT = "tt"
    TN = "tn"
    TR = "tr"
    TM = "tm"
    TC = "tc"
    TV = "tv"
    UG = "ug"
    UA = "ua"
    AE = "ae"
    GB = "gb"
    UM = "um"
    US = "us"
    UY = "uy"
    UZ = "uz"
    VU = "vu"
    VE = "ve"
    VN = "vn"
    VG = "vg"
    VI = "vi"
    WF = "wf"
    EH = "eh"
    YE = "ye"
    ZM = "zm"
    ZW = "zw"
    AX = "ax"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, CountryCode._member_map_.values()))
